/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface RecipientInterface extends utils.Interface {
  functions: {
    "changeData(uint256,string)": FunctionFragment;
    "receivedMessage()": FunctionFragment;
    "receivedValue()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "changeData" | "receivedMessage" | "receivedValue"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeData",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "receivedMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receivedValue",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "changeData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receivedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receivedValue",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Recipient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RecipientInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    changeData(
      _value: BigNumberish,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    receivedMessage(overrides?: CallOverrides): Promise<[string]>;

    receivedValue(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  changeData(
    _value: BigNumberish,
    _message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  receivedMessage(overrides?: CallOverrides): Promise<string>;

  receivedValue(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    changeData(
      _value: BigNumberish,
      _message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    receivedMessage(overrides?: CallOverrides): Promise<string>;

    receivedValue(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    changeData(
      _value: BigNumberish,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    receivedMessage(overrides?: CallOverrides): Promise<BigNumber>;

    receivedValue(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    changeData(
      _value: BigNumberish,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    receivedMessage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receivedValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
