/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface DAOInterface extends utils.Interface {
  functions: {
    "_chainperson()": FunctionFragment;
    "_duration()": FunctionFragment;
    "_minimumQuorum()": FunctionFragment;
    "_token()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_chainperson"
      | "_duration"
      | "_minimumQuorum"
      | "_token"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_chainperson",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_duration", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_minimumQuorum",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_token", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "_chainperson",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_duration", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_minimumQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_token", data: BytesLike): Result;

  events: {};
}

export interface DAO extends BaseContract {
  connect(ownerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DAOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _chainperson(overrides?: CallOverrides): Promise<[string]>;

    _duration(overrides?: CallOverrides): Promise<[BigNumber]>;

    _minimumQuorum(overrides?: CallOverrides): Promise<[BigNumber]>;

    _token(overrides?: CallOverrides): Promise<[string]>;
  };

  _chainperson(overrides?: CallOverrides): Promise<string>;

  _duration(overrides?: CallOverrides): Promise<BigNumber>;

  _minimumQuorum(overrides?: CallOverrides): Promise<BigNumber>;

  _token(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _chainperson(overrides?: CallOverrides): Promise<string>;

    _duration(overrides?: CallOverrides): Promise<BigNumber>;

    _minimumQuorum(overrides?: CallOverrides): Promise<BigNumber>;

    _token(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _chainperson(overrides?: CallOverrides): Promise<BigNumber>;

    _duration(overrides?: CallOverrides): Promise<BigNumber>;

    _minimumQuorum(overrides?: CallOverrides): Promise<BigNumber>;

    _token(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _chainperson(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _duration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _minimumQuorum(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _token(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
